name: Deploy to cPanel

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    name: 🛠️ Build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: ⚙️ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        
    - name: 📦 Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev
      
    - name: ⚙️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: 📦 Install NPM Dependencies & Build
      run: |
        npm install
        npm run build

    - name: 🗂️ Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          public/build/
        retention-days: 1

  deploy:
    name: 🚀 Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📥 Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: .

    - name: 🛠️ Un-ignore public/build
      run: sed -i '\|/public/build|d' .gitignore || true

    - name: 📂 Sync files to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          tests/**
          .env
          .env.example
